### ISSUE TITLE
Add gradient magnitude parameter

### ISSUE THREAD

**Issue by lucasc896** [janfreyberg/pytorch-revgrad#3]
Would be great to have a learnable alpha parameter to vary the magnitude of the flipped gradient as per the original Ganin paper. Happy to throw together a PR for this

**Comment by janfreyberg** [comment]
Great idea. Would be really nice to have that, yep. Go for it!

**Comment by lucasc896** [comment]
Great! I've got the PR ready, but not sure I'm able to push my branch. Can you give me write permissions? Thanks

**Comment by janfreyberg** [comment]
Done - another option would be for you to fork the repository (top right corner), but I've sent you an invite.

**Comment by lucasc896** [comment]
Thanks. I've created the [PR](https://github.com/janfreyberg/pytorch-revgrad/pull/4), but totally up to you if you'd like it in there or not. Thought it'd be nice to have everything in one package for others to make use of 👍
